### ISSUE TITLE
Possible change to net/http API

### ISSUE THREAD

**Issue by fhs** [crazcalm/serve-it#1]
Nice presentation in today's meetup! You may want to keep an eye on https://github.com/golang/go/issues/20759

**Comment by crazcalm** [comment]
Thanks!

So, before today, i would completely agree with the need to add a FileServer that hides dot files in the standard library. However, one of the people at the meetup explained how you would go about wrapping the existing http.FileServer (and http.File) to hide dot files to me and it seems really easy (nested structs and maybe 25 lines of code).

After being shown this, the real issue seems to be that there is no documentation or examples on how to go about doing this. 

That is something that i can fix via blogging and PR requests to the Golang repo (note: go 1.11 is on a code freeze, so go 1.12 will be my goal). So i will work on that next week! :)

**Comment by crazcalm** [comment]
I just wrote some sample code that wraps the http.FileSystem to create a server that hides and denies access to dot files.

https://github.com/crazcalm/my-go-questions/blob/master/what_if/http.fileServer/hide_dot_files.go

I will blog about it sometime this coming week. Then I will try to get an example in the go project.

**Comment by crazcalm** [comment]
I have blogged about the proper way to create a custom file server ([post](https://crazcalm.github.io/blog/post/custom_file_server/)), I have twitted about it, and I have left a comment on the golang issue you shared with me volunteering to write the needed documentation.

Now I wait for their reply and see where everything goes from there.

**Comment by fhs** [comment]
Adding an example to the official docs seems like a good idea.

Note that you can avoid an open system call by doing the dot file check before you call Open:
```Go
func (fs myFileSystem) Open(name string) (http.File, error) {
	if isDotFile(name) { // If dot file, return 403 response
		return nil, os.ErrPermission
	}
	file, err := fs.FileSystem.Open(name)
	return myFile{file}, err
}
```

**Comment by crazcalm** [comment]
Understood. Thanks!
I am not going to change the blog post, but I did update the source code link in the serve-it readme to the following. Thanks again!

    func (fs myFileSystem) Open(name string) (file http.File, err error) {
	    if isDotFile(name) { //If dot file return 403 response
		    return file, os.ErrPermission
	    }
	    file, err = fs.FileSystem.Open(name)
	    return myFile{file}, err
    }

**Comment by crazcalm** [comment]
@fhs Just wanted to circle back and say that you were right about that change. My PR to add an example to the golang source code is currently in the review process, and I have had to make your change plus many others.

Thanks!

**Comment by crazcalm** [comment]
Given that i have written a blog post and sent in a PR to go, i think i have done everything i can for this issue. It's closing time.
